/**
 * Shared report types — safe for client and server.
 * ANALYSIS_ONLY: reports never trigger orders.
 */

export const REPORT_PERIOD_TYPES = ["daily", "weekly", "monthly", "annual"] as const;
export type ReportPeriodType = (typeof REPORT_PERIOD_TYPES)[number];

export const REPORT_PERIOD_LABELS: Record<ReportPeriodType, string> = {
  daily: "Informe diario",
  weekly: "Informe semanal",
  monthly: "Informe mensual",
  annual: "Informe anual",
};

export type ReportEquityPoint = {
  readonly index: number;
  readonly equity: number;
};

export type ReportMetricRow = {
  readonly label: string;
  readonly value: string;
};

export type ReportSection = {
  readonly id: string;
  readonly title: string;
  readonly state: "READY" | "NO_DATA" | "PARTIAL";
  readonly lines: readonly string[];
  readonly metrics?: readonly ReportMetricRow[];
};

export type ReportComparativeSummary = {
  readonly paperPnl: string;
  readonly shadowPnl: string;
  readonly matchedCount: number;
  readonly compareRows: number;
  readonly note: string;
};

/** On-disk artifact paths relative to repo cwd (immutable after write). */
export type ReportArtifactRefs = {
  readonly jsonPath: string;
  readonly htmlPath: string | null;
  readonly pdfPath: string | null;
};

export type ReportEmailDeliveryStatus = {
  readonly attempted: boolean;
  readonly sent: false;
  readonly enabled: boolean;
  readonly reason: string;
};

/** Immutable persisted report document — never mutate after write. */
export type InvestmentPeriodReport = {
  readonly id: string;
  readonly generatedAt: string;
  readonly periodType: ReportPeriodType;
  readonly periodKey: string;
  readonly title: string;
  readonly version: number;
  readonly mode: "ANALYSIS_ONLY";
  readonly orderExecution: "disabled";
  readonly liveTradingEnabled: false;
  readonly sourceSnapshots: readonly string[];
  readonly summaryMetrics: readonly ReportMetricRow[];
  readonly sections: readonly ReportSection[];
  readonly comparative: ReportComparativeSummary;
  readonly paperEquityCurve: readonly ReportEquityPoint[];
  readonly shadowEquityCurve: readonly ReportEquityPoint[];
  readonly markdownBody: string;
  readonly note: string;
  /** Optional file artifacts (daily PDF pipeline and future exports). */
  readonly artifacts?: ReportArtifactRefs;
  /** Email delivery stub status — never sends when disabled. */
  readonly email?: ReportEmailDeliveryStatus;
};

export type ReportHistoryIndex = {
  readonly updatedAt: string;
  readonly mode: "ANALYSIS_ONLY";
  readonly orderExecution: "disabled";
  /** Append-only list of report ids (newest last). */
  readonly ids: readonly string[];
};

export type ReportListFilters = {
  readonly periodType?: ReportPeriodType | "ALL" | string;
  readonly periodKey?: string;
  readonly q?: string;
  readonly from?: string;
  readonly to?: string;
  readonly limit?: number;
};

export type ReportListItem = {
  readonly id: string;
  readonly generatedAt: string;
  readonly periodType: ReportPeriodType;
  readonly periodKey: string;
  readonly title: string;
  readonly version: number;
  readonly paperPnl: string;
  readonly shadowPnl: string;
  readonly note: string;
};

export type ReportsCenterSnapshot = {
  readonly generatedAt: string;
  readonly mode: "ANALYSIS_ONLY";
  readonly orderExecution: "disabled";
  readonly liveTradingEnabled: false;
  readonly autoGenerated: readonly string[];
  readonly total: number;
  readonly items: readonly ReportListItem[];
  readonly selected: InvestmentPeriodReport | null;
  readonly compareWith: InvestmentPeriodReport | null;
  readonly availablePeriodKeys: readonly string[];
  readonly note: string;
};
