import { seedMeta, slugId } from "../seed-helpers";
import type { BusinessModelEntry } from "./types";

export const BUSINESS_MODEL_CATALOG: BusinessModelEntry[] = [
  {
    id: slugId("bm", "saas"),
    domain: "business-models",
    title: "SaaS",
    description: "Software como servicio con ingresos recurrentes y onboarding digital.",
    tags: ["saas", "subscription", "b2b", "web"],
    ...seedMeta(["ceo", "founder", "marketing"]),
    revenueStreams: ["Suscripción mensual/anual", "Add-ons", "Soporte premium"],
    pricingModel: "Tiered subscription",
    targetSegment: "B2B",
    examples: ["Slack", "HubSpot", "Notion"],
  },
  {
    id: slugId("bm", "marketplace"),
    domain: "business-models",
    title: "Marketplace",
    description: "Intermediación entre oferta y demanda con comisión por transacción.",
    tags: ["marketplace", "b2c", "b2b"],
    ...seedMeta(["ceo", "founder", "research"]),
    revenueStreams: ["Comisión por transacción", "Listados destacados", "Suscripción supply-side"],
    pricingModel: "Take rate",
    targetSegment: "B2B2C",
    examples: ["Airbnb", "Uber", "Shopify App Store"],
  },
  {
    id: slugId("bm", "freemium"),
    domain: "business-models",
    title: "Freemium",
    description: "Producto gratuito con límites y upgrade a planes de pago.",
    tags: ["freemium", "b2c", "saas"],
    ...seedMeta(["ceo", "marketing", "product"]),
    revenueStreams: ["Conversión a premium", "Upsell de features", "Publicidad opcional"],
    pricingModel: "Free + paid tiers",
    targetSegment: "B2C",
    examples: ["Duolingo", "Canva", "Spotify"],
  },
  {
    id: slugId("bm", "comision"),
    domain: "business-models",
    title: "Comisión",
    description: "Ingresos porcentuales sobre cada venta o lead cerrado.",
    tags: ["marketplace", "b2b", "b2c"],
    ...seedMeta(["ceo", "founder"]),
    revenueStreams: ["% por venta", "Fee fijo por transacción", "Success fee"],
    pricingModel: "Commission",
    targetSegment: "B2B2C",
    examples: ["Stripe", "Booking.com", "Fiverr"],
  },
  {
    id: slugId("bm", "licencia"),
    domain: "business-models",
    title: "Licencia",
    description: "Venta de licencia de software o IP con contratos anuales.",
    tags: ["saas", "b2b", "enterprise"],
    ...seedMeta(["ceo", "legal"]),
    revenueStreams: ["Licencia anual", "Mantenimiento", "Implementación"],
    pricingModel: "License + maintenance",
    targetSegment: "B2B",
    examples: ["SAP", "Oracle", "Microsoft Enterprise"],
  },
  {
    id: slugId("bm", "publicidad"),
    domain: "business-models",
    title: "Publicidad",
    description: "Monetización por impresiones, clics o inventario de audiencia.",
    tags: ["b2c", "mobile", "web"],
    ...seedMeta(["marketing", "ceo"]),
    revenueStreams: ["Ads display", "Sponsored listings", "Affiliate"],
    pricingModel: "Ad-based",
    targetSegment: "B2C",
    examples: ["Google", "Meta", "TikTok"],
  },
  {
    id: slugId("bm", "lead-generation"),
    domain: "business-models",
    title: "Lead generation",
    description: "Captura y venta de leads cualificados a proveedores.",
    tags: ["b2b", "marketplace"],
    ...seedMeta(["marketing", "founder"]),
    revenueStreams: ["CPL", "Suscripción de acceso", "Premium leads"],
    pricingModel: "Cost per lead",
    targetSegment: "B2B",
    examples: ["Houzz Pro", "Thumbtack", "G2"],
  },
  {
    id: slugId("bm", "suscripcion-b2c"),
    domain: "business-models",
    title: "Suscripción B2C",
    description: "Membresía recurrente para consumidores con contenido o servicio continuo.",
    tags: ["subscription", "b2c", "mobile"],
    ...seedMeta(["marketing", "product"]),
    revenueStreams: ["Mensual", "Anual con descuento", "Familia/equipo"],
    pricingModel: "Consumer subscription",
    targetSegment: "B2C",
    examples: ["Netflix", "Duolingo Plus", "Headspace"],
  },
  {
    id: slugId("bm", "suscripcion-b2b"),
    domain: "business-models",
    title: "Suscripción B2B",
    description: "Contrato recurrente por asiento, uso o módulo para empresas.",
    tags: ["subscription", "b2b", "saas"],
    ...seedMeta(["ceo", "marketing"]),
    revenueStreams: ["Per seat", "Usage-based", "Platform fee"],
    pricingModel: "B2B subscription",
    targetSegment: "B2B",
    examples: ["Monday", "Airtable", "HubSpot"],
  },
];
