/**
 * PROGRAM 6100 — Configurable concurrency limits.
 */

export interface ConcurrencyLimits {
  MAX_GLOBAL_EXECUTIONS: number;
  MAX_WORKSPACE_EXECUTIONS: number;
  MAX_VENTURE_EXECUTIONS: number;
  MAX_AI_EXECUTIONS: number;
  MAX_CODE_BUILDS: number;
  MAX_PREVIEW_SANDBOXES: number;
  MAX_DEPLOYMENT_EXECUTIONS: number;
}

export const DEFAULT_CONCURRENCY_LIMITS: ConcurrencyLimits = {
  MAX_GLOBAL_EXECUTIONS: 20,
  MAX_WORKSPACE_EXECUTIONS: 10,
  MAX_VENTURE_EXECUTIONS: 5,
  MAX_AI_EXECUTIONS: 3,
  MAX_CODE_BUILDS: 3,
  MAX_PREVIEW_SANDBOXES: 3,
  MAX_DEPLOYMENT_EXECUTIONS: 2,
};

export function readConcurrencyLimits(): ConcurrencyLimits {
  const env = process.env;
  return {
    MAX_GLOBAL_EXECUTIONS: parseInt(env.FORGEOS_MAX_GLOBAL_EXECUTIONS || "", 10) || DEFAULT_CONCURRENCY_LIMITS.MAX_GLOBAL_EXECUTIONS,
    MAX_WORKSPACE_EXECUTIONS: parseInt(env.FORGEOS_MAX_WORKSPACE_EXECUTIONS || "", 10) || DEFAULT_CONCURRENCY_LIMITS.MAX_WORKSPACE_EXECUTIONS,
    MAX_VENTURE_EXECUTIONS: parseInt(env.FORGEOS_MAX_VENTURE_EXECUTIONS || "", 10) || DEFAULT_CONCURRENCY_LIMITS.MAX_VENTURE_EXECUTIONS,
    MAX_AI_EXECUTIONS: parseInt(env.FORGEOS_MAX_AI_EXECUTIONS || "", 10) || DEFAULT_CONCURRENCY_LIMITS.MAX_AI_EXECUTIONS,
    MAX_CODE_BUILDS: parseInt(env.FORGEOS_MAX_CODE_BUILDS || "", 10) || DEFAULT_CONCURRENCY_LIMITS.MAX_CODE_BUILDS,
    MAX_PREVIEW_SANDBOXES: parseInt(env.FORGEOS_MAX_PREVIEW_SANDBOXES || "", 10) || DEFAULT_CONCURRENCY_LIMITS.MAX_PREVIEW_SANDBOXES,
    MAX_DEPLOYMENT_EXECUTIONS: parseInt(env.FORGEOS_MAX_DEPLOYMENT_EXECUTIONS || "", 10) || DEFAULT_CONCURRENCY_LIMITS.MAX_DEPLOYMENT_EXECUTIONS,
  };
}
