/** ForgeOS AI Runtime RC6 — seed model data. */

import type { RegisteredModel } from "../types";

const cap = (
  overrides: Partial<RegisteredModel["capabilities"]> = {}
): RegisteredModel["capabilities"] => ({
  tools: true,
  vision: false,
  images: false,
  audio: false,
  reasoning: false,
  json: true,
  streaming: true,
  ...overrides,
});

export const SEED_MODELS: RegisteredModel[] = [
  {
    id: "openai-gpt-4o",
    provider: "openai",
    model: "gpt-4o",
    version: "2024-08",
    label: "GPT-4o",
    capabilities: cap({ vision: true }),
    pricing: { inputPer1k: 0.005, outputPer1k: 0.015 },
    latencyMs: 1800,
    contextWindow: 128000,
    priority: 90,
    health: "healthy",
    specialty: ["general", "code", "product"],
  },
  {
    id: "anthropic-claude-sonnet",
    provider: "anthropic",
    model: "claude-sonnet-4-20250514",
    version: "4.0",
    label: "Claude Sonnet 4",
    capabilities: cap({ reasoning: true, vision: true }),
    pricing: { inputPer1k: 0.003, outputPer1k: 0.015 },
    latencyMs: 2200,
    contextWindow: 200000,
    priority: 95,
    health: "healthy",
    specialty: ["reasoning", "executive", "json"],
  },
  {
    id: "google-gemini-15-pro",
    provider: "google",
    model: "gemini-1.5-pro",
    version: "1.5",
    label: "Gemini 1.5 Pro",
    capabilities: cap({ vision: true, audio: true }),
    pricing: { inputPer1k: 0.0025, outputPer1k: 0.01 },
    latencyMs: 1600,
    contextWindow: 1000000,
    priority: 85,
    health: "healthy",
    specialty: ["research", "multimodal"],
  },
  {
    id: "openrouter-gpt-4o",
    provider: "openrouter",
    model: "openai/gpt-4o",
    version: "routed",
    label: "OpenRouter GPT-4o",
    capabilities: cap({ vision: true }),
    pricing: { inputPer1k: 0.005, outputPer1k: 0.015 },
    latencyMs: 2000,
    contextWindow: 128000,
    priority: 80,
    health: "healthy",
    specialty: ["multi-model", "fallback"],
  },
  {
    id: "deepseek-chat",
    provider: "deepseek",
    model: "deepseek-chat",
    version: "v3",
    label: "DeepSeek Chat",
    capabilities: cap({ reasoning: true }),
    pricing: { inputPer1k: 0.0003, outputPer1k: 0.001 },
    latencyMs: 1400,
    contextWindow: 64000,
    priority: 75,
    health: "healthy",
    specialty: ["code", "cost-efficient"],
  },
  {
    id: "mistral-large",
    provider: "mistral",
    model: "mistral-large-latest",
    version: "latest",
    label: "Mistral Large",
    capabilities: cap(),
    pricing: { inputPer1k: 0.003, outputPer1k: 0.009 },
    latencyMs: 1200,
    contextWindow: 128000,
    priority: 70,
    health: "healthy",
    specialty: ["classification", "eu"],
  },
  {
    id: "llama-33-70b",
    provider: "llama",
    model: "llama-3.3-70b-versatile",
    version: "3.3",
    label: "Llama 3.3 70B",
    capabilities: cap({ tools: false }),
    pricing: { inputPer1k: 0.0005, outputPer1k: 0.0008 },
    latencyMs: 900,
    contextWindow: 128000,
    priority: 65,
    health: "healthy",
    specialty: ["open-weights", "low-latency"],
  },
  {
    id: "azure-gpt-4o",
    provider: "azure-openai",
    model: "gpt-4o",
    version: "azure",
    label: "Azure GPT-4o",
    capabilities: cap({ vision: true }),
    pricing: { inputPer1k: 0.005, outputPer1k: 0.015 },
    latencyMs: 2000,
    contextWindow: 128000,
    priority: 88,
    health: "unknown",
    specialty: ["enterprise", "compliance"],
  },
  {
    id: "aws-bedrock-claude",
    provider: "aws-bedrock",
    model: "anthropic.claude-3-sonnet-20240229-v1:0",
    version: "bedrock",
    label: "Bedrock Claude 3 Sonnet",
    capabilities: cap({ reasoning: true }),
    pricing: { inputPer1k: 0.003, outputPer1k: 0.015 },
    latencyMs: 2400,
    contextWindow: 200000,
    priority: 60,
    health: "unknown",
    specialty: ["enterprise", "aws"],
  },
  {
    id: "vertex-gemini",
    provider: "vertex-ai",
    model: "gemini-1.5-pro",
    version: "vertex",
    label: "Vertex Gemini 1.5 Pro",
    capabilities: cap({ vision: true }),
    pricing: { inputPer1k: 0.0025, outputPer1k: 0.01 },
    latencyMs: 1900,
    contextWindow: 1000000,
    priority: 82,
    health: "unknown",
    specialty: ["google-cloud", "research"],
  },
  {
    id: "ollama-llama32",
    provider: "ollama",
    model: "llama3.2",
    version: "local",
    label: "Ollama Llama 3.2",
    capabilities: cap({ tools: false }),
    pricing: { inputPer1k: 0, outputPer1k: 0 },
    latencyMs: 3000,
    contextWindow: 128000,
    priority: 40,
    health: "unknown",
    specialty: ["local", "privacy"],
  },
  {
    id: "lmstudio-local",
    provider: "lmstudio",
    model: "local-model",
    version: "local",
    label: "LM Studio Local",
    capabilities: cap({ tools: false }),
    pricing: { inputPer1k: 0, outputPer1k: 0 },
    latencyMs: 3500,
    contextWindow: 32000,
    priority: 35,
    health: "unknown",
    specialty: ["local", "desktop"],
  },
];
