/** ForgeOS Worker Runtime — official worker definitions (Epic 4.3). */

import { cap } from "./worker-capabilities";
import type { WorkerDefinition } from "./types";
import type { VentureState } from "../state-machine/types";

const V = "1.0.0";

const ALL_ACTIVE: VentureState[] = [
  "IDEA", "DISCOVERY", "RESEARCH", "PRODUCT", "ARCHITECTURE", "UX",
  "BUILD", "QA", "LAUNCH", "GROWTH", "SCALE", "CAPITAL",
];

const EARLY: VentureState[] = ["IDEA", "DISCOVERY", "RESEARCH", "PRODUCT"];
const PRODUCT_PHASE: VentureState[] = ["RESEARCH", "PRODUCT", "ARCHITECTURE", "UX"];
const BUILD_PHASE: VentureState[] = ["ARCHITECTURE", "UX", "BUILD", "QA"];
const LAUNCH_PHASE: VentureState[] = ["QA", "LAUNCH", "GROWTH"];
const GROWTH_PHASE: VentureState[] = ["LAUNCH", "GROWTH", "SCALE", "CAPITAL"];

export const OFFICIAL_WORKERS: WorkerDefinition[] = [
  {
    id: "ceo",
    name: "CEO",
    description: "Executive decision-maker — venture direction, approvals, and board coordination.",
    department: "executive",
    capabilities: cap("strategic_decisions", "board_coordination", "venture_approval"),
    priority: "P0_CRITICAL",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: [...ALL_ACTIVE, "PAUSED", "BLOCKED"],
    supportedTasks: ["CEO_REVIEW", "BOARD_REVIEW", "DISCOVERY_REVIEW", "RISK_REVIEW", "EXECUTIVE_BRIEF"],
    version: V,
  },
  {
    id: "research",
    name: "Research",
    description: "Market research, competitor analysis, source validation, and hypothesis testing.",
    department: "research",
    capabilities: cap("market_research", "competitor_analysis", "source_validation", "validation"),
    priority: "P1_HIGH",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: ["DISCOVERY", "RESEARCH", "PRODUCT"],
    supportedTasks: ["RESEARCH_RUN", "SOURCE_ANALYSIS", "COMPETITOR_ANALYSIS", "DISCOVERY_REVIEW"],
    version: V,
  },
  {
    id: "product",
    name: "Product",
    description: "PRD authoring, user stories, and product scope definition.",
    department: "product",
    capabilities: cap("prd_authoring", "user_stories", "scope_definition"),
    priority: "P1_HIGH",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: PRODUCT_PHASE,
    supportedTasks: ["PRODUCT_UPDATE", "UPDATE_PRD", "GENERATE_USER_STORIES"],
    version: V,
  },
  {
    id: "ux",
    name: "UX",
    description: "User flows, wireframes, and usability review.",
    department: "design",
    capabilities: cap("user_flows", "wireframes", "usability"),
    priority: "P2_MEDIUM",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: ["PRODUCT", "ARCHITECTURE", "UX", "BUILD"],
    supportedTasks: ["GENERATE_FLOWS", "GENERATE_WIREFRAMES", "UX_REVIEW"],
    version: V,
  },
  {
    id: "architecture",
    name: "Architecture",
    description: "System design, API contracts, and infrastructure planning.",
    department: "engineering",
    capabilities: cap("system_design", "api_design", "infrastructure"),
    priority: "P1_HIGH",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: ["PRODUCT", "ARCHITECTURE", "BUILD"],
    supportedTasks: ["BUILD_PLAN_UPDATE", "DESIGN_SYSTEM", "API_SPECS", "ARCHITECTURE_REVIEW"],
    version: V,
  },
  {
    id: "cto",
    name: "CTO",
    description: "Technology strategy, stack decisions, and engineering quality gates.",
    department: "engineering",
    capabilities: cap("tech_strategy", "code_review", "system_design"),
    priority: "P0_CRITICAL",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: BUILD_PHASE,
    supportedTasks: ["TECH_REVIEW", "STACK_DECISION", "BUILD_PLAN_UPDATE", "CODE_REVIEW"],
    version: V,
  },
  {
    id: "backend",
    name: "Backend",
    description: "API implementation, services, and database integration.",
    department: "engineering",
    capabilities: cap("api_implementation", "services", "database_integration", "api_design"),
    priority: "P1_HIGH",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: BUILD_PHASE,
    supportedTasks: ["API_IMPLEMENTATION", "SERVICE_DESIGN", "BUILD_EXECUTE"],
    version: V,
  },
  {
    id: "frontend",
    name: "Frontend",
    description: "UI implementation and responsive design.",
    department: "engineering",
    capabilities: cap("ui_implementation", "responsive_design"),
    priority: "P1_HIGH",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: ["UX", "BUILD", "QA"],
    supportedTasks: ["UI_IMPLEMENTATION", "COMPONENT_BUILD", "BUILD_EXECUTE"],
    version: V,
  },
  {
    id: "database",
    name: "Database",
    description: "Schema design, migrations, and data modeling.",
    department: "engineering",
    capabilities: cap("schema_design", "migrations", "data_modeling"),
    priority: "P2_MEDIUM",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: ["ARCHITECTURE", "BUILD"],
    supportedTasks: ["SCHEMA_DESIGN", "MIGRATION", "DATA_MODEL_REVIEW"],
    version: V,
  },
  {
    id: "qa",
    name: "QA",
    description: "Testing, accessibility, performance, and security review.",
    department: "quality",
    capabilities: cap("testing", "accessibility", "performance", "security_review"),
    priority: "P1_HIGH",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: ["BUILD", "QA", "LAUNCH"],
    supportedTasks: ["GENERATE_TEST_PLAN", "CHECK_ACCESSIBILITY", "CHECK_PERFORMANCE", "SECURITY_SCAN"],
    version: V,
  },
  {
    id: "marketing",
    name: "Marketing",
    description: "Messaging, campaigns, and content strategy.",
    department: "growth",
    capabilities: cap("messaging", "campaigns", "content"),
    priority: "P2_MEDIUM",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: LAUNCH_PHASE,
    supportedTasks: ["CAMPAIGN_PLAN", "MESSAGING", "OPPORTUNITY_REVIEW"],
    version: V,
  },
  {
    id: "growth",
    name: "Growth",
    description: "Acquisition, retention, and growth experiments.",
    department: "growth",
    capabilities: cap("acquisition", "retention", "experiments", "funnel_analysis"),
    priority: "P2_MEDIUM",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: GROWTH_PHASE,
    supportedTasks: ["GROWTH_EXPERIMENT", "FUNNEL_ANALYSIS", "OPPORTUNITY_REVIEW", "SIMULATOR_UPDATE"],
    version: V,
  },
  {
    id: "finance",
    name: "Finance",
    description: "Financial modeling, budgeting, and risk assessment.",
    department: "finance",
    capabilities: cap("financial_modeling", "budgeting", "risk_assessment"),
    priority: "P1_HIGH",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: [...EARLY, "GROWTH", "SCALE", "CAPITAL"],
    supportedTasks: ["FINANCIAL_MODEL", "BUDGET_REVIEW", "RISK_REVIEW", "SIMULATOR_UPDATE"],
    version: V,
  },
  {
    id: "legal",
    name: "Legal",
    description: "Compliance, contracts, and IP protection.",
    department: "legal",
    capabilities: cap("compliance", "contracts", "ip_protection"),
    priority: "P1_HIGH",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: [...ALL_ACTIVE, "PAUSED"],
    supportedTasks: ["COMPLIANCE_REVIEW", "CONTRACT_DRAFT", "RISK_REVIEW"],
    version: V,
  },
  {
    id: "operations",
    name: "Operations",
    description: "Process design, SLA management, and vendor coordination.",
    department: "operations",
    capabilities: cap("process_design", "sla_management", "vendor_management"),
    priority: "P2_MEDIUM",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: ["LAUNCH", "GROWTH", "SCALE"],
    supportedTasks: ["PROCESS_DESIGN", "SLA_SETUP", "VENDOR_ONBOARD"],
    version: V,
  },
  {
    id: "support",
    name: "Support",
    description: "Ticket triage, knowledge base, and customer success.",
    department: "operations",
    capabilities: cap("ticket_triage", "knowledge_base", "customer_success"),
    priority: "P2_MEDIUM",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: ["LAUNCH", "GROWTH", "SCALE"],
    supportedTasks: ["TICKET_TRIAGE", "KB_ARTICLE", "CUSTOMER_ONBOARD"],
    version: V,
  },
  {
    id: "capital",
    name: "Capital",
    description: "Fundraising, investor relations, and valuation.",
    department: "capital",
    capabilities: cap("fundraising", "investor_relations", "valuation"),
    priority: "P0_CRITICAL",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: ["SCALE", "CAPITAL", "EXIT"],
    supportedTasks: ["FUNDING_PREP", "INVESTOR_BRIEF", "OPPORTUNITY_REVIEW"],
    version: V,
  },
  {
    id: "knowledge",
    name: "Knowledge",
    description: "Memory writes, documentation, and knowledge indexing.",
    department: "knowledge",
    capabilities: cap("memory_write", "documentation", "indexing"),
    priority: "P2_MEDIUM",
    requiredContext: ["ventureId"],
    allowedStates: [...ALL_ACTIVE, "PAUSED", "BLOCKED", "ARCHIVED"],
    supportedTasks: ["MEMORY_WRITE", "DOC_INDEX", "KNOWLEDGE_SYNC"],
    version: V,
  },
  {
    id: "analytics",
    name: "Analytics",
    description: "Metrics reporting, data analysis, and funnel analysis.",
    department: "analytics",
    capabilities: cap("metrics_reporting", "data_analysis", "funnel_analysis"),
    priority: "P2_MEDIUM",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: GROWTH_PHASE,
    supportedTasks: ["METRICS_REPORT", "DASHBOARD_SETUP", "SIMULATOR_UPDATE"],
    version: V,
  },
  {
    id: "build",
    name: "Build",
    description: "Build execution and build plan review.",
    department: "build",
    capabilities: cap("build_execution", "build_planning"),
    priority: "P0_CRITICAL",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: ["BUILD", "QA"],
    supportedTasks: ["BUILD_EXECUTE", "BUILD_PLAN_REVIEW", "BUILD_PLAN_UPDATE"],
    version: V,
  },
  {
    id: "deployment",
    name: "Deployment",
    description: "CI/CD, staging and production deployment, monitoring setup.",
    department: "deployment",
    capabilities: cap("ci_cd", "staging_deploy", "production_deploy", "monitoring"),
    priority: "P1_HIGH",
    requiredContext: ["ventureId", "ventureState"],
    allowedStates: ["BUILD", "QA", "LAUNCH"],
    supportedTasks: ["DEPLOY_STAGING", "DEPLOY_PRODUCTION", "MONITORING_SETUP"],
    version: V,
  },
];

export function registerOfficialWorkers(
  registry: { register(def: WorkerDefinition): unknown },
): void {
  for (const worker of OFFICIAL_WORKERS) {
    registry.register(worker);
  }
}

export function getOfficialWorkerDefinition(id: string): WorkerDefinition | undefined {
  return OFFICIAL_WORKERS.find((w) => w.id === id);
}
