/** Storage key constants for intelligence layer localStorage. */

export const STORAGE_KEYS = {
  decisions: "forgeos-intelligence-decisions",
  ventureMemory: "forgeos-intelligence-venture-memory",
  portfolio: "forgeos-intelligence-portfolio",
  patterns: "forgeos-intelligence-patterns",
  learning: "forgeos-intelligence-learning",
  ceoMemory: "forgeos-intelligence-ceo-memory",
  knowledgeEvolution: "forgeos-intelligence-knowledge-evolution",
  history: "forgeos-intelligence-history",
  aiOrchestrationExecutions: "forgeos-ai-orchestration-executions",
  executiveRuntime: "forgeos-executive-runtime-memory",
  executiveGraph: "forgeos-executive-decision-graph",
  executiveObservability: "forgeos-executive-observability",
  aiRuntimeTelemetry: "forgeos-ai-runtime-telemetry",
  aiRuntimeTelemetryV2: "forgeos-ai-runtime-telemetry-v2",
  aiRuntimeRouting: "forgeos-ai-runtime-routing",
  aiRuntimeMemory: "forgeos-ai-runtime-memory",
  executiveMeshSessions: "forgeos-executive-mesh-sessions",
  executiveMeshDebates: "forgeos-executive-mesh-debates",
  executiveMeshScores: "forgeos-executive-mesh-scores",
  executiveMeshMeetings: "forgeos-executive-mesh-meetings",
  skillAuditLogs: "forgeos-skill-audit-logs",
  skillTelemetry: "forgeos-skill-telemetry",
  skillMemory: "forgeos-skill-memory",
  skillQueue: "forgeos-skill-queue",
  skillGovernanceApprovals: "forgeos-skill-governance-approvals",
  skillGovernanceAudit: "forgeos-skill-governance-audit",
  skillGovernanceTelemetry: "forgeos-skill-governance-telemetry",
  skillGovernanceHistory: "forgeos-skill-governance-history",
  skillGovernanceEvents: "forgeos-skill-governance-events",
  skillStoreCatalog: "forgeos-skill-store-catalog",
  skillStoreInstalled: "forgeos-skill-store-installed",
  skillStoreMarketplace: "forgeos-skill-store-marketplace",
  capabilityHistory: "forgeos-capability-history",
  capabilityTelemetry: "forgeos-capability-telemetry",
  capabilityMetrics: "forgeos-capability-metrics",
  capabilityEvents: "forgeos-capability-events",
  capabilityStore: "forgeos-capability-store",
  autonomousOrganization: "forgeos-autonomous-organization",
  enterpriseState: "forgeos-enterprise-state",
  enterpriseAudit: "forgeos-enterprise-audit",
  enterpriseUsage: "forgeos-enterprise-usage",
} as const;

export type StorageKey = (typeof STORAGE_KEYS)[keyof typeof STORAGE_KEYS];
