/** PROGRAM 5360 — Shared generator utilities. */

import type { TemplateContext } from "../templates/types";
import {
  dependenciesToPackageJson,
  devDependenciesToPackageJson,
} from "../dependency-builder";
import type { TemplateManifest } from "../templates/types";
import type { CodeDependency } from "../types";

export function extractModulesFromIdea(ideaText: string): string[] {
  const keywords: Record<string, string[]> = {
    technicians: ["técnico", "technician", "campo", "field"],
    clients: ["cliente", "client", "customer"],
    work_orders: ["incidencia", "orden", "work order", "ticket", "servicio"],
    routes: ["ruta", "route", "dispatch"],
    inventory: ["inventario", "inventory", "stock", "almacén"],
    billing: ["factura", "billing", "invoice", "cobro"],
    dashboard: ["dashboard", "panel", "métrica"],
    auth: ["auth", "login", "usuario", "rol"],
  };

  const lower = ideaText.toLowerCase();
  const modules: string[] = [];
  for (const [mod, words] of Object.entries(keywords)) {
    if (words.some((w) => lower.includes(w))) modules.push(mod);
  }
  if (modules.length === 0) modules.push("dashboard", "auth");
  return modules;
}

export function buildPackageJson(
  slug: string,
  manifest: TemplateManifest,
  deps: CodeDependency[]
): string {
  return JSON.stringify(
    {
      name: slug,
      version: "0.1.0",
      private: true,
      scripts: manifest.scripts,
      dependencies: dependenciesToPackageJson(deps),
      devDependencies: devDependenciesToPackageJson(deps),
    },
    null,
    2
  );
}

export function buildTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        paths: { "@/*": ["./*"] },
      },
      include: ["**/*.ts", "**/*.tsx"],
      exclude: ["node_modules"],
    },
    null,
    2
  );
}

export function buildReadme(ctx: TemplateContext, stack: string): string {
  return `# ${ctx.ventureName}

> ${ctx.ideaText.slice(0, 120)}

Generated by ForgeOS Code Generation (template). This project is **autonomous** — no ForgeOS internals.

## Stack

${stack}

## Getting started

\`\`\`bash
npm install
cp .env.example .env.local
npm run dev
\`\`\`

## Modules

${ctx.modules.map((m) => `- ${m}`).join("\n")}

## Notes

- Static validation only — compile verification is separate (5370)
- No real credentials — use .env.example placeholders
`;
}

export function pascalCase(s: string): string {
  return s
    .split(/[-_]/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

export function fhisButton(name: string): string {
  return `/** FHIS-compatible inline component — autonomous, no ForgeOS imports */
import clsx from "clsx";

interface ${name}Props {
  children: React.ReactNode;
  variant?: "primary" | "secondary" | "ghost";
  onClick?: () => void;
  type?: "button" | "submit";
  disabled?: boolean;
}

export function ${name}({ children, variant = "primary", onClick, type = "button", disabled }: ${name}Props) {
  return (
    <button
      type={type}
      onClick={onClick}
      disabled={disabled}
      className={clsx(
        "inline-flex items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition",
        variant === "primary" && "bg-blue-600 text-white hover:bg-blue-700",
        variant === "secondary" && "border border-gray-300 bg-white hover:bg-gray-50",
        variant === "ghost" && "text-gray-700 hover:bg-gray-100",
        disabled && "opacity-50 cursor-not-allowed"
      )}
    >
      {children}
    </button>
  );
}
`;
}
