/** ForgeOS Capability Layer — registry (RC4.9). */

import { defineCapability, CATEGORY_DEFAULTS } from "./capability";
import type { CapabilityDefinition } from "./types";

const CAPABILITY_REGISTRY: CapabilityDefinition[] = [
  // Development
  defineCapability({
    id: "create_repository",
    name: "Create Repository",
    category: "development",
    description: "Provision a new source code repository with default branch protection",
    authorizedDepartments: ["cto", "backend", "frontend", "deployment"],
    compatibleWorkers: ["dev-worker", "repo-worker"],
    compatibleSkills: ["github", "gitlab", "bitbucket"],
    compatibleProviders: ["github", "gitlab", "bitbucket"],
    ...CATEGORY_DEFAULTS.development,
    risk: "medium",
  }),
  defineCapability({
    id: "create_branch",
    name: "Create Branch",
    category: "development",
    description: "Create a feature or release branch in version control",
    authorizedDepartments: ["cto", "backend", "frontend", "qa"],
    compatibleWorkers: ["dev-worker"],
    compatibleSkills: ["github", "gitlab"],
    compatibleProviders: ["github", "gitlab"],
    ...CATEGORY_DEFAULTS.development,
    risk: "low",
    estimatedCost: 0.01,
    estimatedLatency: 1500,
  }),
  defineCapability({
    id: "open_pull_request",
    name: "Open Pull Request",
    category: "development",
    description: "Open a pull request for code review and merge",
    authorizedDepartments: ["cto", "backend", "frontend", "qa"],
    compatibleWorkers: ["dev-worker", "review-worker"],
    compatibleSkills: ["github", "gitlab"],
    compatibleProviders: ["github", "gitlab"],
    ...CATEGORY_DEFAULTS.development,
    risk: "low",
  }),
  defineCapability({
    id: "generate_application",
    name: "Generate Application",
    category: "development",
    description: "Scaffold a new application from ForgeOS templates",
    authorizedDepartments: ["cto", "cpo", "product", "architecture"],
    compatibleWorkers: ["factory-worker", "scaffold-worker"],
    compatibleSkills: ["github", "openai-skill", "claude-skill"],
    compatibleProviders: ["github", "openai", "anthropic"],
    ...CATEGORY_DEFAULTS.development,
    estimatedCost: 0.25,
    estimatedLatency: 15000,
  }),
  defineCapability({
    id: "deploy_software",
    name: "Deploy Software",
    category: "development",
    description: "Orchestrate multi-skill deployment pipeline (CI/CD, infra, notify)",
    authorizedDepartments: ["cto", "deployment", "infrastructure", "qa"],
    compatibleWorkers: ["deploy-worker", "ops-worker"],
    compatibleSkills: [
      "github",
      "docker",
      "vercel",
      "cloudflare",
      "supabase",
      "slack",
      "knowledge",
      "timeline",
      "memory",
    ],
    compatibleProviders: [
      "github",
      "docker",
      "vercel",
      "cloudflare",
      "supabase",
      "slack",
    ],
    ...CATEGORY_DEFAULTS.development,
    risk: "high",
    estimatedCost: 0.45,
    estimatedLatency: 20000,
    priority: "critical",
  }),
  defineCapability({
    id: "create_database",
    name: "Create Database",
    category: "development",
    description: "Provision database schema and connection for a venture",
    authorizedDepartments: ["cto", "backend", "infrastructure"],
    compatibleWorkers: ["db-worker"],
    compatibleSkills: ["supabase", "postgres", "neon"],
    compatibleProviders: ["supabase", "neon", "aws"],
    ...CATEGORY_DEFAULTS.development,
    risk: "high",
  }),
  defineCapability({
    id: "create_infrastructure",
    name: "Create Infrastructure",
    category: "development",
    description: "Provision cloud infrastructure resources (sandbox mock)",
    authorizedDepartments: ["cto", "infrastructure", "deployment"],
    compatibleWorkers: ["infra-worker"],
    compatibleSkills: ["aws", "gcp", "azure", "cloudflare", "terraform"],
    compatibleProviders: ["aws", "gcp", "azure", "cloudflare"],
    ...CATEGORY_DEFAULTS.development,
    risk: "critical",
    estimatedCost: 0.3,
  }),
  defineCapability({
    id: "create_environment",
    name: "Create Environment",
    category: "development",
    description: "Create staging or production environment configuration",
    authorizedDepartments: ["cto", "deployment", "infrastructure"],
    compatibleWorkers: ["env-worker"],
    compatibleSkills: ["vercel", "netlify", "docker", "github"],
    compatibleProviders: ["vercel", "netlify", "docker"],
    ...CATEGORY_DEFAULTS.development,
    risk: "medium",
  }),
  defineCapability({
    id: "configure_domain",
    name: "Configure Domain",
    category: "development",
    description: "Plan and configure DNS/domain via Cloudflare (dry-run default)",
    authorizedDepartments: ["cto", "deployment", "infrastructure"],
    compatibleWorkers: ["dns-worker", "ops-worker"],
    compatibleSkills: ["cloudflare", "vercel"],
    compatibleProviders: ["cloudflare", "vercel"],
    ...CATEGORY_DEFAULTS.development,
    risk: "high",
    estimatedCost: 0.05,
    estimatedLatency: 5000,
  }),

  // Productivity
  defineCapability({
    id: "send_email",
    name: "Send Email",
    category: "productivity",
    description: "Send transactional or notification email (sandbox)",
    authorizedDepartments: ["ceo", "coo", "customer-success", "support"],
    compatibleWorkers: ["comms-worker"],
    compatibleSkills: ["sendgrid", "resend", "gmail"],
    compatibleProviders: ["sendgrid", "resend", "google"],
    ...CATEGORY_DEFAULTS.productivity,
  }),
  defineCapability({
    id: "schedule_meeting",
    name: "Schedule Meeting",
    category: "productivity",
    description: "Schedule executive or team meeting",
    authorizedDepartments: ["ceo", "coo", "cpo"],
    compatibleWorkers: ["calendar-worker"],
    compatibleSkills: ["google-calendar", "outlook", "calendly"],
    compatibleProviders: ["google", "microsoft", "calendly"],
    ...CATEGORY_DEFAULTS.productivity,
  }),
  defineCapability({
    id: "create_document",
    name: "Create Document",
    category: "productivity",
    description: "Create a new document in knowledge base",
    authorizedDepartments: ["ceo", "cpo", "product", "knowledge"],
    compatibleWorkers: ["doc-worker"],
    compatibleSkills: ["notion", "google-docs", "confluence"],
    compatibleProviders: ["notion", "google", "atlassian"],
    ...CATEGORY_DEFAULTS.productivity,
  }),
  defineCapability({
    id: "update_document",
    name: "Update Document",
    category: "productivity",
    description: "Update existing venture documentation",
    authorizedDepartments: ["ceo", "cpo", "product", "knowledge"],
    compatibleWorkers: ["doc-worker"],
    compatibleSkills: ["notion", "google-docs", "confluence"],
    compatibleProviders: ["notion", "google", "atlassian"],
    ...CATEGORY_DEFAULTS.productivity,
  }),

  // Marketing
  defineCapability({
    id: "publish_campaign",
    name: "Publish Campaign",
    category: "marketing",
    description: "Launch marketing campaign across channels (sandbox)",
    authorizedDepartments: ["cmo", "growth"],
    compatibleWorkers: ["campaign-worker"],
    compatibleSkills: ["meta-ads", "google-ads", "mailchimp", "hubspot"],
    compatibleProviders: ["meta", "google", "mailchimp"],
    ...CATEGORY_DEFAULTS.marketing,
    risk: "high",
  }),
  defineCapability({
    id: "create_ad",
    name: "Create Ad",
    category: "marketing",
    description: "Create ad creative and targeting configuration",
    authorizedDepartments: ["cmo", "growth"],
    compatibleWorkers: ["ads-worker"],
    compatibleSkills: ["meta-ads", "google-ads", "tiktok-ads"],
    compatibleProviders: ["meta", "google", "tiktok"],
    ...CATEGORY_DEFAULTS.marketing,
  }),

  // Research
  defineCapability({
    id: "analyze_competitors",
    name: "Analyze Competitors",
    category: "research",
    description: "Competitive landscape analysis for venture positioning",
    authorizedDepartments: ["research", "cpo", "cmo"],
    compatibleWorkers: ["research-worker"],
    compatibleSkills: ["openai-skill", "claude-skill", "perplexity", "notion"],
    compatibleProviders: ["openai", "anthropic", "perplexity"],
    ...CATEGORY_DEFAULTS.research,
  }),
  defineCapability({
    id: "search_information",
    name: "Search Information",
    category: "research",
    description: "Search internal and external knowledge sources",
    authorizedDepartments: ["research", "knowledge", "ceo"],
    compatibleWorkers: ["search-worker"],
    compatibleSkills: ["perplexity", "openai-skill", "notion"],
    compatibleProviders: ["perplexity", "openai", "notion"],
    ...CATEGORY_DEFAULTS.research,
  }),

  // Business
  defineCapability({
    id: "create_invoice",
    name: "Create Invoice",
    category: "business",
    description: "Generate customer invoice (sandbox)",
    authorizedDepartments: ["cfo", "finance", "sales"],
    compatibleWorkers: ["finance-worker"],
    compatibleSkills: ["stripe", "quickbooks", "xero"],
    compatibleProviders: ["stripe", "quickbooks", "xero"],
    ...CATEGORY_DEFAULTS.business,
  }),
  defineCapability({
    id: "send_invoice",
    name: "Send Invoice",
    category: "business",
    description: "Send invoice to customer via email",
    authorizedDepartments: ["cfo", "finance"],
    compatibleWorkers: ["finance-worker"],
    compatibleSkills: ["stripe", "sendgrid", "quickbooks"],
    compatibleProviders: ["stripe", "sendgrid"],
    ...CATEGORY_DEFAULTS.business,
  }),
  defineCapability({
    id: "create_contract",
    name: "Create Contract",
    category: "business",
    description: "Draft legal contract from template",
    authorizedDepartments: ["legal", "cfo", "sales"],
    compatibleWorkers: ["legal-worker"],
    compatibleSkills: ["docusign", "pandadoc", "notion"],
    compatibleProviders: ["docusign", "pandadoc"],
    ...CATEGORY_DEFAULTS.business,
    risk: "critical",
  }),
  defineCapability({
    id: "sign_contract",
    name: "Sign Contract",
    category: "business",
    description: "Execute contract signature workflow (sandbox)",
    authorizedDepartments: ["legal", "ceo", "cfo"],
    compatibleWorkers: ["legal-worker"],
    compatibleSkills: ["docusign", "pandadoc"],
    compatibleProviders: ["docusign", "pandadoc"],
    ...CATEGORY_DEFAULTS.business,
    risk: "critical",
  }),

  // Analytics
  defineCapability({
    id: "analyze_metrics",
    name: "Analyze Metrics",
    category: "analytics",
    description: "Analyze venture KPIs and performance metrics",
    authorizedDepartments: ["analytics", "cfo", "cpo", "ceo"],
    compatibleWorkers: ["analytics-worker"],
    compatibleSkills: ["mixpanel", "amplitude", "google-analytics", "stripe"],
    compatibleProviders: ["mixpanel", "amplitude", "google"],
    ...CATEGORY_DEFAULTS.analytics,
  }),
  defineCapability({
    id: "generate_dashboard",
    name: "Generate Dashboard",
    category: "analytics",
    description: "Generate executive dashboard from metrics",
    authorizedDepartments: ["analytics", "ceo", "cfo"],
    compatibleWorkers: ["dashboard-worker"],
    compatibleSkills: ["metabase", "looker", "notion"],
    compatibleProviders: ["metabase", "looker"],
    ...CATEGORY_DEFAULTS.analytics,
    estimatedLatency: 8000,
  }),

  // Project
  defineCapability({
    id: "create_project",
    name: "Create Project",
    category: "project",
    description: "Create venture project with milestones",
    authorizedDepartments: ["cpo", "coo", "product"],
    compatibleWorkers: ["project-worker"],
    compatibleSkills: ["linear", "jira", "notion", "asana"],
    compatibleProviders: ["linear", "atlassian", "notion"],
    ...CATEGORY_DEFAULTS.project,
  }),
  defineCapability({
    id: "manage_roadmap",
    name: "Manage Roadmap",
    category: "project",
    description: "Update product roadmap and priorities",
    authorizedDepartments: ["cpo", "product", "ceo"],
    compatibleWorkers: ["roadmap-worker"],
    compatibleSkills: ["linear", "notion", "productboard"],
    compatibleProviders: ["linear", "notion"],
    ...CATEGORY_DEFAULTS.project,
  }),

  // Venture / Build
  defineCapability({
    id: "create_venture",
    name: "Create Venture",
    category: "venture",
    description: "Initialize new venture in ForgeOS portfolio",
    authorizedDepartments: ["ceo", "capital"],
    compatibleWorkers: ["venture-worker"],
    compatibleSkills: ["notion", "github", "openai-skill"],
    compatibleProviders: ["notion", "github"],
    ...CATEGORY_DEFAULTS.venture,
  }),
  defineCapability({
    id: "validate_startup",
    name: "Validate Startup",
    category: "venture",
    description: "Run startup validation checklist and scoring",
    authorizedDepartments: ["ceo", "research", "capital"],
    compatibleWorkers: ["validation-worker"],
    compatibleSkills: ["openai-skill", "claude-skill", "notion"],
    compatibleProviders: ["openai", "anthropic"],
    ...CATEGORY_DEFAULTS.venture,
  }),
  defineCapability({
    id: "execute_research",
    name: "Execute Research",
    category: "venture",
    description: "Execute venture research phase with memory capture",
    authorizedDepartments: ["research", "cpo"],
    compatibleWorkers: ["research-worker"],
    compatibleSkills: ["perplexity", "openai-skill", "notion", "memory"],
    compatibleProviders: ["perplexity", "openai"],
    ...CATEGORY_DEFAULTS.venture,
  }),
  defineCapability({
    id: "generate_prd",
    name: "Generate PRD",
    category: "venture",
    description: "Generate product requirements document",
    authorizedDepartments: ["cpo", "product"],
    compatibleWorkers: ["prd-worker"],
    compatibleSkills: ["openai-skill", "claude-skill", "notion"],
    compatibleProviders: ["openai", "anthropic"],
    ...CATEGORY_DEFAULTS.venture,
    estimatedCost: 0.15,
  }),
  defineCapability({
    id: "generate_architecture",
    name: "Generate Architecture",
    category: "venture",
    description: "Generate system architecture specification",
    authorizedDepartments: ["cto", "architecture"],
    compatibleWorkers: ["arch-worker"],
    compatibleSkills: ["openai-skill", "claude-skill", "notion", "mermaid"],
    compatibleProviders: ["openai", "anthropic"],
    ...CATEGORY_DEFAULTS.venture,
    estimatedCost: 0.18,
  }),
  defineCapability({
    id: "generate_ux",
    name: "Generate UX",
    category: "venture",
    description: "Generate UX flows and wireframes specification",
    authorizedDepartments: ["cpo", "ux", "product"],
    compatibleWorkers: ["ux-worker"],
    compatibleSkills: ["figma", "openai-skill", "notion"],
    compatibleProviders: ["figma", "openai"],
    ...CATEGORY_DEFAULTS.venture,
  }),
  defineCapability({
    id: "generate_frontend",
    name: "Generate Frontend",
    category: "venture",
    description: "Generate frontend application scaffold",
    authorizedDepartments: ["frontend", "cto"],
    compatibleWorkers: ["frontend-worker"],
    compatibleSkills: ["github", "vercel", "openai-skill"],
    compatibleProviders: ["github", "vercel"],
    ...CATEGORY_DEFAULTS.venture,
    estimatedCost: 0.35,
    estimatedLatency: 25000,
  }),
  defineCapability({
    id: "generate_backend",
    name: "Generate Backend",
    category: "venture",
    description: "Generate backend API scaffold",
    authorizedDepartments: ["backend", "cto"],
    compatibleWorkers: ["backend-worker"],
    compatibleSkills: ["github", "docker", "openai-skill"],
    compatibleProviders: ["github", "docker"],
    ...CATEGORY_DEFAULTS.venture,
    estimatedCost: 0.35,
    estimatedLatency: 25000,
  }),
  defineCapability({
    id: "generate_database",
    name: "Generate Database",
    category: "venture",
    description: "Generate database schema and migrations",
    authorizedDepartments: ["backend", "infrastructure"],
    compatibleWorkers: ["db-worker"],
    compatibleSkills: ["supabase", "postgres", "prisma"],
    compatibleProviders: ["supabase", "neon"],
    ...CATEGORY_DEFAULTS.venture,
  }),
  defineCapability({
    id: "execute_qa",
    name: "Execute QA",
    category: "venture",
    description: "Run QA test suite and report results",
    authorizedDepartments: ["qa", "cto"],
    compatibleWorkers: ["qa-worker"],
    compatibleSkills: ["github", "playwright", "cypress"],
    compatibleProviders: ["github", "playwright"],
    ...CATEGORY_DEFAULTS.venture,
    estimatedLatency: 12000,
  }),
  defineCapability({
    id: "prepare_release",
    name: "Prepare Release",
    category: "venture",
    description: "Prepare release notes, changelog, and version bump",
    authorizedDepartments: ["deployment", "cpo", "qa"],
    compatibleWorkers: ["release-worker"],
    compatibleSkills: ["github", "notion", "slack"],
    compatibleProviders: ["github", "slack"],
    ...CATEGORY_DEFAULTS.venture,
  }),
  defineCapability({
    id: "publish_release",
    name: "Publish Release",
    category: "venture",
    description: "Publish release to production (sandbox orchestration)",
    authorizedDepartments: ["deployment", "ceo", "cto"],
    compatibleWorkers: ["release-worker", "deploy-worker"],
    compatibleSkills: ["github", "vercel", "docker", "slack", "cloudflare"],
    compatibleProviders: ["github", "vercel", "cloudflare"],
    ...CATEGORY_DEFAULTS.venture,
    risk: "critical",
    estimatedCost: 0.5,
    priority: "critical",
  }),
];

export function listAllCapabilities(): CapabilityDefinition[] {
  return [...CAPABILITY_REGISTRY];
}

export function getCapabilityById(id: string): CapabilityDefinition | undefined {
  const found = CAPABILITY_REGISTRY.find((c) => c.id === id);
  if (found) return found;
  if (id === "DISABLED_CAPABILITY" || id === "UNAVAILABLE_SKILL") {
    return defineCapability({
      id: "DISABLED_CAPABILITY",
      name: "Disabled Capability",
      category: "development",
      description: "Capability unavailable in current environment",
      authorizedDepartments: ["ceo"],
      compatibleWorkers: [],
      compatibleSkills: ["UNAVAILABLE_SKILL"],
      compatibleProviders: ["UNKNOWN_PROVIDER"],
      ...CATEGORY_DEFAULTS.development,
      status: "disabled",
      health: "unavailable",
      risk: "low",
    });
  }
  return undefined;
}

export function getCapabilitiesByCategory(
  category: CapabilityDefinition["category"]
): CapabilityDefinition[] {
  return CAPABILITY_REGISTRY.filter((c) => c.category === category);
}

export function getCapabilityHealthSummary(): {
  total: number;
  healthy: number;
  degraded: number;
  unavailable: number;
  active: number;
} {
  const all = listAllCapabilities();
  return {
    total: all.length,
    healthy: all.filter((c) => c.health === "healthy").length,
    degraded: all.filter((c) => c.health === "degraded").length,
    unavailable: all.filter((c) => c.health === "unavailable").length,
    active: all.filter((c) => c.status === "active" || c.status === "sandbox").length,
  };
}

export function getCapabilityCount(): number {
  return CAPABILITY_REGISTRY.length;
}
