/** RC9 — Ecosystem pack catalog (mock / sandbox). */

import type { EcosystemPack } from "./types";

export const ECOSYSTEM_PACK_CATALOG: EcosystemPack[] = [
  {
    id: "eco-pack-crm",
    name: "CRM Business Pack",
    packType: "business-packs",
    version: "1.2.0",
    description:
      "Paquete completo de CRM: pipeline de ventas, contactos, automatización y reporting para el CEO.",
    tags: ["crm", "sales", "customer", "pipeline", "hubspot"],
    publisher: "ForgeOS Partners",
    status: "active",
    updatedAt: "2026-07-01T10:00:00.000Z",
    priceLabel: "€49/mes",
    dependencies: ["hubspot", "email", "business-billing", "eco-plugin-crm-sync"],
    capabilities: ["crm.pipeline", "crm.contacts", "crm.automation", "crm.reporting"],
    featured: true,
    rating: 4.8,
    reviewCount: 142,
    installCount: 2840,
  },
  {
    id: "eco-pack-ai-ceo",
    name: "AI CEO Assistant Pack",
    packType: "ai-packs",
    version: "2.0.1",
    description: "Capacidades de IA ejecutiva: briefings, decisiones y análisis estratégico.",
    tags: ["ai", "ceo", "executive", "reasoning"],
    publisher: "ForgeOS Official",
    status: "active",
    updatedAt: "2026-06-15T08:00:00.000Z",
    priceLabel: "Free",
    dependencies: ["openai-skill", "claude-skill"],
    capabilities: ["ai.briefing", "ai.decision", "ai.strategy"],
    featured: true,
    rating: 4.9,
    reviewCount: 89,
    installCount: 5120,
  },
  {
    id: "eco-pack-growth",
    name: "Growth Marketing Pack",
    packType: "business-packs",
    version: "1.0.3",
    description: "Playbooks de crecimiento, campañas y analytics integrados.",
    tags: ["growth", "marketing", "analytics", "campaigns"],
    publisher: "Growth Labs",
    status: "beta",
    updatedAt: "2026-06-20T12:00:00.000Z",
    priceLabel: "€29/mes",
    dependencies: ["marketing-analytics", "ga4", "pack-growth-prompts"],
    capabilities: ["growth.campaigns", "growth.funnels", "growth.analytics"],
    rating: 4.5,
    reviewCount: 56,
    installCount: 890,
  },
  {
    id: "eco-cap-sales",
    name: "Sales Capability Layer",
    packType: "capabilities",
    version: "1.1.0",
    description: "Capa de capacidades de ventas para el mesh ejecutivo.",
    tags: ["capabilities", "sales", "crm"],
    publisher: "ForgeOS Official",
    status: "active",
    updatedAt: "2026-05-10T09:00:00.000Z",
    priceLabel: "Free",
    dependencies: ["hubspot"],
    capabilities: ["cap.sales.outreach", "cap.sales.pipeline"],
    rating: 4.6,
    reviewCount: 34,
    installCount: 1200,
  },
  {
    id: "eco-plugin-crm-sync",
    name: "CRM Sync Plugin",
    packType: "plugins",
    version: "0.9.2",
    description: "Plugin sandbox para sincronización bidireccional de CRM.",
    tags: ["plugin", "crm", "sync", "integration"],
    publisher: "Integrations Co",
    status: "sandbox",
    updatedAt: "2026-07-02T14:00:00.000Z",
    priceLabel: "€9/mes",
    dependencies: ["hubspot"],
    capabilities: ["plugin.crm.sync", "plugin.webhook"],
    rating: 4.2,
    reviewCount: 18,
    installCount: 340,
  },
  {
    id: "eco-plugin-analytics",
    name: "Analytics Bridge Plugin",
    packType: "plugins",
    version: "1.0.0",
    description: "Conecta fuentes de analytics al venture workspace (sandbox).",
    tags: ["plugin", "analytics", "ga4"],
    publisher: "DataForge",
    status: "active",
    updatedAt: "2026-06-01T11:00:00.000Z",
    priceLabel: "Free",
    dependencies: ["ga4"],
    capabilities: ["plugin.analytics.ingest"],
    rating: 4.4,
    reviewCount: 27,
    installCount: 670,
  },
  {
    id: "eco-knowledge-playbook",
    name: "Venture Playbook Knowledge",
    packType: "knowledge-packs",
    version: "1.3.0",
    description: "Base de conocimiento con playbooks de venture building.",
    tags: ["knowledge", "playbook", "venture"],
    publisher: "ForgeOS Academy",
    status: "active",
    updatedAt: "2026-04-20T16:00:00.000Z",
    priceLabel: "€19",
    dependencies: ["pack-venture-playbook"],
    capabilities: ["knowledge.playbooks", "knowledge.templates"],
    skillStoreItemId: "pack-venture-playbook",
    rating: 4.7,
    reviewCount: 91,
    installCount: 1560,
  },
  {
    id: "eco-dept-revenue",
    name: "Revenue Department Pack",
    packType: "departments",
    version: "1.0.0",
    description: "Departamento de ingresos con workers y skills preconfigurados.",
    tags: ["department", "revenue", "sales"],
    publisher: "ForgeOS Official",
    status: "active",
    updatedAt: "2026-05-05T10:00:00.000Z",
    priceLabel: "Free",
    dependencies: ["hubspot", "stripe"],
    capabilities: ["dept.revenue", "dept.sales-ops"],
    rating: 4.5,
    reviewCount: 44,
    installCount: 980,
  },
];

export function getEcosystemPackById(id: string): EcosystemPack | undefined {
  return ECOSYSTEM_PACK_CATALOG.find((p) => p.id === id);
}

export function getCrmDemoPack(): EcosystemPack {
  const pack = getEcosystemPackById("eco-pack-crm");
  if (!pack) throw new Error("CRM demo pack not found");
  return pack;
}
