import { seedMeta, slugId } from "../seed-helpers";
import type { ArchitectureEntry } from "./types";

export const ARCHITECTURE_CATALOG: ArchitectureEntry[] = [
  {
    id: slugId("architecture", "saas-web"),
    domain: "architecture",
    title: "SaaS web",
    description: "Aplicación web multi-tenant con autenticación, billing y panel de administración.",
    tags: ["saas", "web", "b2b", "subscription"],
    ...seedMeta(["cto", "backend", "frontend"]),
    stack: ["Next.js", "PostgreSQL", "Stripe", "Auth"],
    scalability: "high",
    useCases: ["Herramientas B2B", "Dashboards", "Workflows internos"],
    tradeoffs: ["Mayor complejidad de permisos", "Necesita observabilidad desde día uno"],
  },
  {
    id: slugId("architecture", "marketplace"),
    domain: "architecture",
    title: "Marketplace",
    description: "Plataforma bilateral con listados, reservas/transacciones y reputación.",
    tags: ["marketplace", "web", "b2c", "b2b"],
    ...seedMeta(["cto", "backend", "product"]),
    stack: ["Next.js", "PostgreSQL", "Payments", "Search"],
    scalability: "medium",
    useCases: ["Reservas", "Servicios locales", "Matching oferta-demanda"],
    tradeoffs: ["Cold start bilateral", "Fraude y disputas", "Take rate vs CAC"],
  },
  {
    id: slugId("architecture", "mobile-app"),
    domain: "architecture",
    title: "Mobile app",
    description: "Cliente móvil con API backend, notificaciones push y sincronización offline ligera.",
    tags: ["mobile", "b2c", "api"],
    ...seedMeta(["cto", "frontend"]),
    stack: ["React Native", "API REST", "Push notifications", "Analytics"],
    scalability: "high",
    useCases: ["Consumo diario", "On-the-go", "Geolocalización"],
    tradeoffs: ["Doble release iOS/Android", "Mayor coste de mantenimiento"],
  },
  {
    id: slugId("architecture", "ai-assistant"),
    domain: "architecture",
    title: "AI assistant",
    description: "Copiloto conversacional con RAG, herramientas y trazabilidad de prompts.",
    tags: ["ai", "saas", "web", "api"],
    ...seedMeta(["cto", "backend", "product"]),
    stack: ["LLM API", "Vector DB", "Queue", "Guardrails"],
    scalability: "medium",
    useCases: ["Soporte", "Research", "Generación de documentos"],
    tradeoffs: ["Coste variable por token", "Alucinaciones", "Latencia"],
  },
  {
    id: slugId("architecture", "dashboard-app"),
    domain: "architecture",
    title: "Dashboard app",
    description: "Panel analítico con KPIs, filtros y exportación de datos.",
    tags: ["dashboard", "saas", "b2b", "analytics"],
    ...seedMeta(["cto", "frontend", "ux"]),
    stack: ["Next.js", "Charts", "Warehouse/API", "RBAC"],
    scalability: "high",
    useCases: ["Reporting", "Operaciones", "Monitoreo"],
    tradeoffs: ["Riesgo de scope creep en visualizaciones", "Performance con datasets grandes"],
  },
  {
    id: slugId("architecture", "crm"),
    domain: "architecture",
    title: "CRM",
    description: "Gestión de pipeline, contactos, actividades y automatizaciones comerciales.",
    tags: ["crm", "saas", "b2b"],
    ...seedMeta(["cto", "product", "backend"]),
    stack: ["Next.js", "PostgreSQL", "Email sync", "Workflow engine"],
    scalability: "high",
    useCases: ["Ventas B2B", "Account management", "Soporte comercial"],
    tradeoffs: ["Integraciones CRM existentes", "Adopción por equipos de venta"],
  },
  {
    id: slugId("architecture", "erp-ligero"),
    domain: "architecture",
    title: "ERP ligero",
    description: "Módulos de inventario, facturación y operaciones para pymes.",
    tags: ["erp", "saas", "b2b"],
    ...seedMeta(["cto", "database", "backend"]),
    stack: ["Next.js", "PostgreSQL", "Ledger", "Multi-entity"],
    scalability: "medium",
    useCases: ["Retail", "Distribución", "Servicios con stock"],
    tradeoffs: ["Alta complejidad funcional", "Migración desde Excel"],
  },
  {
    id: slugId("architecture", "booking-reservas"),
    domain: "architecture",
    title: "Booking / reservas",
    description: "Calendario, disponibilidad, pagos y confirmaciones para reservas.",
    tags: ["marketplace", "mobile", "web", "b2c"],
    ...seedMeta(["cto", "backend", "ux"]),
    stack: ["Calendar API", "Payments", "Notifications", "PostgreSQL"],
    scalability: "medium",
    useCases: ["Clínicas", "Deporte", "Hostelería"],
    tradeoffs: ["No-shows", "Sincronización de calendarios externos"],
  },
];
