// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activity">> = Specific
  const handler = {} as typeof import("../../app/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/migration-v2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/migration-v2">> = Specific
  const handler = {} as typeof import("../../app/admin/migration-v2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents">> = Specific
  const handler = {} as typeof import("../../app/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai">> = Specific
  const handler = {} as typeof import("../../app/ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alerts">> = Specific
  const handler = {} as typeof import("../../app/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api-keys/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/api-keys">> = Specific
  const handler = {} as typeof import("../../app/api-keys/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/application-factory/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/application-factory/[projectId]">> = Specific
  const handler = {} as typeof import("../../app/application-factory/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/application-factory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/application-factory">> = Specific
  const handler = {} as typeof import("../../app/application-factory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/benchmarks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/benchmarks">> = Specific
  const handler = {} as typeof import("../../app/benchmarks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/beta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/beta">> = Specific
  const handler = {} as typeof import("../../app/beta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/billing">> = Specific
  const handler = {} as typeof import("../../app/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/build/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/build/[id]">> = Specific
  const handler = {} as typeof import("../../app/build/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/capital/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/capital">> = Specific
  const handler = {} as typeof import("../../app/capital/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ceo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ceo">> = Specific
  const handler = {} as typeof import("../../app/ceo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/changelog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/changelog">> = Specific
  const handler = {} as typeof import("../../app/changelog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cloud/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cloud">> = Specific
  const handler = {} as typeof import("../../app/cloud/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/command-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/command-center">> = Specific
  const handler = {} as typeof import("../../app/command-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/community/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/community">> = Specific
  const handler = {} as typeof import("../../app/community/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/company/[ventureId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company/[ventureId]">> = Specific
  const handler = {} as typeof import("../../app/company/[ventureId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/company/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/company">> = Specific
  const handler = {} as typeof import("../../app/company/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/creator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/creator">> = Specific
  const handler = {} as typeof import("../../app/creator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer-success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer-success">> = Specific
  const handler = {} as typeof import("../../app/customer-success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/demo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/demo">> = Specific
  const handler = {} as typeof import("../../app/demo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/deployments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/deployments">> = Specific
  const handler = {} as typeof import("../../app/deployments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/design-partners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-partners">> = Specific
  const handler = {} as typeof import("../../app/design-partners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/design-system/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/design-system">> = Specific
  const handler = {} as typeof import("../../app/design-system/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs/[slug]">> = Specific
  const handler = {} as typeof import("../../app/docs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/docs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/docs">> = Specific
  const handler = {} as typeof import("../../app/docs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/engineering/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engineering">> = Specific
  const handler = {} as typeof import("../../app/engineering/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/enterprise/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/enterprise">> = Specific
  const handler = {} as typeof import("../../app/enterprise/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/executive-insights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/executive-insights">> = Specific
  const handler = {} as typeof import("../../app/executive-insights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/feedback-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feedback-center">> = Specific
  const handler = {} as typeof import("../../app/feedback-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/feedback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/feedback">> = Specific
  const handler = {} as typeof import("../../app/feedback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forgot-password">> = Specific
  const handler = {} as typeof import("../../app/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/founder-journey/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/founder-journey">> = Specific
  const handler = {} as typeof import("../../app/founder-journey/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/founder-zero/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/founder-zero">> = Specific
  const handler = {} as typeof import("../../app/founder-zero/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/founder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/founder">> = Specific
  const handler = {} as typeof import("../../app/founder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/health">> = Specific
  const handler = {} as typeof import("../../app/health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ideas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ideas">> = Specific
  const handler = {} as typeof import("../../app/ideas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/incidents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/incidents">> = Specific
  const handler = {} as typeof import("../../app/incidents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/intelligence/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/intelligence/[id]">> = Specific
  const handler = {} as typeof import("../../app/intelligence/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/investors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/investors">> = Specific
  const handler = {} as typeof import("../../app/investors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/ai-collaboration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/ai-collaboration">> = Specific
  const handler = {} as typeof import("../../app/lab/ai-collaboration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/ai-runtime/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/ai-runtime">> = Specific
  const handler = {} as typeof import("../../app/lab/ai-runtime/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/ai-skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/ai-skills">> = Specific
  const handler = {} as typeof import("../../app/lab/ai-skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/analytics-skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/analytics-skills">> = Specific
  const handler = {} as typeof import("../../app/lab/analytics-skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/aurea-facilities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/aurea-facilities">> = Specific
  const handler = {} as typeof import("../../app/lab/aurea-facilities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/autonomous-organization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/autonomous-organization">> = Specific
  const handler = {} as typeof import("../../app/lab/autonomous-organization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/backend-factory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/backend-factory">> = Specific
  const handler = {} as typeof import("../../app/lab/backend-factory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/build-context/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/build-context">> = Specific
  const handler = {} as typeof import("../../app/lab/build-context/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/build-dna/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/build-dna">> = Specific
  const handler = {} as typeof import("../../app/lab/build-dna/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/build-registry/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/build-registry">> = Specific
  const handler = {} as typeof import("../../app/lab/build-registry/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/business-skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/business-skills">> = Specific
  const handler = {} as typeof import("../../app/lab/business-skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/capabilities/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/capabilities">> = Specific
  const handler = {} as typeof import("../../app/lab/capabilities/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/cloud-foundation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/cloud-foundation">> = Specific
  const handler = {} as typeof import("../../app/lab/cloud-foundation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/command-center/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/command-center">> = Specific
  const handler = {} as typeof import("../../app/lab/command-center/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/database-factory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/database-factory">> = Specific
  const handler = {} as typeof import("../../app/lab/database-factory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/developer-skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/developer-skills">> = Specific
  const handler = {} as typeof import("../../app/lab/developer-skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/ecosystem/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/ecosystem">> = Specific
  const handler = {} as typeof import("../../app/lab/ecosystem/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/enterprise/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/enterprise">> = Specific
  const handler = {} as typeof import("../../app/lab/enterprise/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/execution-engine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/execution-engine">> = Specific
  const handler = {} as typeof import("../../app/lab/execution-engine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/executive-mesh/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/executive-mesh">> = Specific
  const handler = {} as typeof import("../../app/lab/executive-mesh/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/executive-runtime/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/executive-runtime">> = Specific
  const handler = {} as typeof import("../../app/lab/executive-runtime/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/forge-capital/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/forge-capital">> = Specific
  const handler = {} as typeof import("../../app/lab/forge-capital/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/founder-zero/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/founder-zero">> = Specific
  const handler = {} as typeof import("../../app/lab/founder-zero/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/frontend-factory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/frontend-factory">> = Specific
  const handler = {} as typeof import("../../app/lab/frontend-factory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/infrastructure-factory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/infrastructure-factory">> = Specific
  const handler = {} as typeof import("../../app/lab/infrastructure-factory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/live-ai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/live-ai">> = Specific
  const handler = {} as typeof import("../../app/lab/live-ai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/live-mission/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/live-mission">> = Specific
  const handler = {} as typeof import("../../app/lab/live-mission/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/marketing-skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/marketing-skills">> = Specific
  const handler = {} as typeof import("../../app/lab/marketing-skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/network/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/network">> = Specific
  const handler = {} as typeof import("../../app/lab/network/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/os-rc2/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/os-rc2">> = Specific
  const handler = {} as typeof import("../../app/lab/os-rc2/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/preview-deployment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/preview-deployment">> = Specific
  const handler = {} as typeof import("../../app/lab/preview-deployment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/preview-runtime/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/preview-runtime">> = Specific
  const handler = {} as typeof import("../../app/lab/preview-runtime/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/production-readiness/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/production-readiness">> = Specific
  const handler = {} as typeof import("../../app/lab/production-readiness/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/productivity-skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/productivity-skills">> = Specific
  const handler = {} as typeof import("../../app/lab/productivity-skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/qa-factory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/qa-factory">> = Specific
  const handler = {} as typeof import("../../app/lab/qa-factory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/rc1/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/rc1">> = Specific
  const handler = {} as typeof import("../../app/lab/rc1/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/real-build-flow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/real-build-flow">> = Specific
  const handler = {} as typeof import("../../app/lab/real-build-flow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/real-connections/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/real-connections">> = Specific
  const handler = {} as typeof import("../../app/lab/real-connections/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/real-execution/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/real-execution">> = Specific
  const handler = {} as typeof import("../../app/lab/real-execution/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/release-manager/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/release-manager">> = Specific
  const handler = {} as typeof import("../../app/lab/release-manager/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/runtime-observability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/runtime-observability">> = Specific
  const handler = {} as typeof import("../../app/lab/runtime-observability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/runtime-scheduler/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/runtime-scheduler">> = Specific
  const handler = {} as typeof import("../../app/lab/runtime-scheduler/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/self-evolution/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/self-evolution">> = Specific
  const handler = {} as typeof import("../../app/lab/self-evolution/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/skill-store/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/skill-store">> = Specific
  const handler = {} as typeof import("../../app/lab/skill-store/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/skills-governance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/skills-governance">> = Specific
  const handler = {} as typeof import("../../app/lab/skills-governance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/skills">> = Specific
  const handler = {} as typeof import("../../app/lab/skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/state-machine/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/state-machine">> = Specific
  const handler = {} as typeof import("../../app/lab/state-machine/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/task-queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/task-queue">> = Specific
  const handler = {} as typeof import("../../app/lab/task-queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/venture-factory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/venture-factory">> = Specific
  const handler = {} as typeof import("../../app/lab/venture-factory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/venture-intelligence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/venture-intelligence">> = Specific
  const handler = {} as typeof import("../../app/lab/venture-intelligence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/website-factory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/website-factory">> = Specific
  const handler = {} as typeof import("../../app/lab/website-factory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/lab/workers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lab/workers">> = Specific
  const handler = {} as typeof import("../../app/lab/workers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/labs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/labs">> = Specific
  const handler = {} as typeof import("../../app/labs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing">> = Specific
  const handler = {} as typeof import("../../app/landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/launch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/launch">> = Specific
  const handler = {} as typeof import("../../app/launch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/live/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/live">> = Specific
  const handler = {} as typeof import("../../app/live/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logs">> = Specific
  const handler = {} as typeof import("../../app/logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/marketplace/agents/[agentId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/agents/[agentId]">> = Specific
  const handler = {} as typeof import("../../app/marketplace/agents/[agentId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/marketplace/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace/agents">> = Specific
  const handler = {} as typeof import("../../app/marketplace/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketplace">> = Specific
  const handler = {} as typeof import("../../app/marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mission-control/[missionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mission-control/[missionId]">> = Specific
  const handler = {} as typeof import("../../app/mission-control/[missionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mission-control/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mission-control">> = Specific
  const handler = {} as typeof import("../../app/mission-control/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/missions/[missionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/missions/[missionId]">> = Specific
  const handler = {} as typeof import("../../app/missions/[missionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mobile-factory/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mobile-factory/[projectId]">> = Specific
  const handler = {} as typeof import("../../app/mobile-factory/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mobile-factory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mobile-factory">> = Specific
  const handler = {} as typeof import("../../app/mobile-factory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitoring">> = Specific
  const handler = {} as typeof import("../../app/monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/network-insights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/network-insights">> = Specific
  const handler = {} as typeof import("../../app/network-insights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/network/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/network">> = Specific
  const handler = {} as typeof import("../../app/network/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/new-app/generating/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/new-app/generating/[id]">> = Specific
  const handler = {} as typeof import("../../app/new-app/generating/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/new-app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/new-app">> = Specific
  const handler = {} as typeof import("../../app/new-app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/nps/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nps">> = Specific
  const handler = {} as typeof import("../../app/nps/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboarding/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding">> = Specific
  const handler = {} as typeof import("../../app/onboarding/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/organization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/organization">> = Specific
  const handler = {} as typeof import("../../app/organization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/os/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/os/analytics">> = Specific
  const handler = {} as typeof import("../../app/os/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/os/build/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/os/build">> = Specific
  const handler = {} as typeof import("../../app/os/build/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/os/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/os/calendar">> = Specific
  const handler = {} as typeof import("../../app/os/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/os/capital/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/os/capital">> = Specific
  const handler = {} as typeof import("../../app/os/capital/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/os/ceo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/os/ceo">> = Specific
  const handler = {} as typeof import("../../app/os/ceo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/os/creator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/os/creator">> = Specific
  const handler = {} as typeof import("../../app/os/creator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/os/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/os/knowledge">> = Specific
  const handler = {} as typeof import("../../app/os/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/os/labs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/os/labs">> = Specific
  const handler = {} as typeof import("../../app/os/labs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/os/marketplace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/os/marketplace">> = Specific
  const handler = {} as typeof import("../../app/os/marketplace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/os/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/os">> = Specific
  const handler = {} as typeof import("../../app/os/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/os/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/os/portfolio">> = Specific
  const handler = {} as typeof import("../../app/os/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/os/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/os/settings">> = Specific
  const handler = {} as typeof import("../../app/os/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/os/workspace/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/os/workspace/[id]">> = Specific
  const handler = {} as typeof import("../../app/os/workspace/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/playbooks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playbooks">> = Specific
  const handler = {} as typeof import("../../app/playbooks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/plugins/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/plugins">> = Specific
  const handler = {} as typeof import("../../app/plugins/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/product-analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/product-analytics">> = Specific
  const handler = {} as typeof import("../../app/product-analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/production/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/production">> = Specific
  const handler = {} as typeof import("../../app/production/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../app/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recovery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recovery">> = Specific
  const handler = {} as typeof import("../../app/recovery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/releases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/releases">> = Specific
  const handler = {} as typeof import("../../app/releases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/resultado/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resultado/[id]">> = Specific
  const handler = {} as typeof import("../../app/resultado/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/roadmap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roadmap">> = Specific
  const handler = {} as typeof import("../../app/roadmap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sdk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sdk">> = Specific
  const handler = {} as typeof import("../../app/sdk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security">> = Specific
  const handler = {} as typeof import("../../app/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/self-evolution/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/self-evolution">> = Specific
  const handler = {} as typeof import("../../app/self-evolution/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/status/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/status">> = Specific
  const handler = {} as typeof import("../../app/status/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/store/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/store">> = Specific
  const handler = {} as typeof import("../../app/store/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/studio/[missionId]/[section]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/[missionId]/[section]">> = Specific
  const handler = {} as typeof import("../../app/studio/[missionId]/[section]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/studio/[missionId]/code/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/[missionId]/code">> = Specific
  const handler = {} as typeof import("../../app/studio/[missionId]/code/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/studio/[missionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/[missionId]">> = Specific
  const handler = {} as typeof import("../../app/studio/[missionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/studio/[missionId]/preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio/[missionId]/preview">> = Specific
  const handler = {} as typeof import("../../app/studio/[missionId]/preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio">> = Specific
  const handler = {} as typeof import("../../app/studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscriptions">> = Specific
  const handler = {} as typeof import("../../app/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/templates">> = Specific
  const handler = {} as typeof import("../../app/templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/venture-factory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/venture-factory">> = Specific
  const handler = {} as typeof import("../../app/venture-factory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/venture/[id]/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/venture/[id]/knowledge">> = Specific
  const handler = {} as typeof import("../../app/venture/[id]/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/venture/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/venture/[id]">> = Specific
  const handler = {} as typeof import("../../app/venture/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/venture/[id]/print/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/venture/[id]/print">> = Specific
  const handler = {} as typeof import("../../app/venture/[id]/print/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/venture/[id]/timeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/venture/[id]/timeline">> = Specific
  const handler = {} as typeof import("../../app/venture/[id]/timeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ventures/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ventures/[slug]">> = Specific
  const handler = {} as typeof import("../../app/ventures/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/waitlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/waitlist">> = Specific
  const handler = {} as typeof import("../../app/waitlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/website-factory/[projectId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/website-factory/[projectId]">> = Specific
  const handler = {} as typeof import("../../app/website-factory/[projectId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/website-factory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/website-factory">> = Specific
  const handler = {} as typeof import("../../app/website-factory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace">> = Specific
  const handler = {} as typeof import("../../app/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ai/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/run">> = Specific
  const handler = {} as typeof import("../../app/api/ai/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/build-pipeline/dry-run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/build-pipeline/dry-run">> = Specific
  const handler = {} as typeof import("../../app/api/build-pipeline/dry-run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/build-pipeline/request-approval/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/build-pipeline/request-approval">> = Specific
  const handler = {} as typeof import("../../app/api/build-pipeline/request-approval/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/build-pipeline/snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/build-pipeline/snapshot">> = Specific
  const handler = {} as typeof import("../../app/api/build-pipeline/snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ceo-workspace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ceo-workspace">> = Specific
  const handler = {} as typeof import("../../app/api/ceo-workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/code-generation/[missionId]/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/code-generation/[missionId]/export">> = Specific
  const handler = {} as typeof import("../../app/api/code-generation/[missionId]/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/code-generation/[missionId]/files/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/code-generation/[missionId]/files">> = Specific
  const handler = {} as typeof import("../../app/api/code-generation/[missionId]/files/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/connections/dry-run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connections/dry-run">> = Specific
  const handler = {} as typeof import("../../app/api/connections/dry-run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/connections/request-approval/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connections/request-approval">> = Specific
  const handler = {} as typeof import("../../app/api/connections/request-approval/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/connections/test/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/connections/test">> = Specific
  const handler = {} as typeof import("../../app/api/connections/test/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/delivery/[missionId]/snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/delivery/[missionId]/snapshot">> = Specific
  const handler = {} as typeof import("../../app/api/delivery/[missionId]/snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/generate/product/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate/product">> = Specific
  const handler = {} as typeof import("../../app/api/generate/product/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/generate/research/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate/research">> = Specific
  const handler = {} as typeof import("../../app/api/generate/research/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/preview-deployment/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preview-deployment/approve">> = Specific
  const handler = {} as typeof import("../../app/api/preview-deployment/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/preview-deployment/draft/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preview-deployment/draft">> = Specific
  const handler = {} as typeof import("../../app/api/preview-deployment/draft/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/preview-deployment/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preview-deployment/execute">> = Specific
  const handler = {} as typeof import("../../app/api/preview-deployment/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/preview-deployment/rollback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preview-deployment/rollback">> = Specific
  const handler = {} as typeof import("../../app/api/preview-deployment/rollback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/preview-deployment/snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preview-deployment/snapshot">> = Specific
  const handler = {} as typeof import("../../app/api/preview-deployment/snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/preview-runtime/[id]/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preview-runtime/[id]/logs">> = Specific
  const handler = {} as typeof import("../../app/api/preview-runtime/[id]/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/preview-runtime/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preview-runtime/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/preview-runtime/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/preview-runtime/docker/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preview-runtime/docker">> = Specific
  const handler = {} as typeof import("../../app/api/preview-runtime/docker/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/preview-runtime/e2e/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preview-runtime/e2e">> = Specific
  const handler = {} as typeof import("../../app/api/preview-runtime/e2e/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/preview-runtime/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preview-runtime">> = Specific
  const handler = {} as typeof import("../../app/api/preview-runtime/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/preview-runtime/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preview-runtime/start">> = Specific
  const handler = {} as typeof import("../../app/api/preview-runtime/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/preview-runtime/stop/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preview-runtime/stop">> = Specific
  const handler = {} as typeof import("../../app/api/preview-runtime/stop/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/real-build-flow/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/real-build-flow/approve">> = Specific
  const handler = {} as typeof import("../../app/api/real-build-flow/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/real-build-flow/controlled-execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/real-build-flow/controlled-execute">> = Specific
  const handler = {} as typeof import("../../app/api/real-build-flow/controlled-execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/real-build-flow/dry-run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/real-build-flow/dry-run">> = Specific
  const handler = {} as typeof import("../../app/api/real-build-flow/dry-run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/real-build-flow/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/real-build-flow/execute">> = Specific
  const handler = {} as typeof import("../../app/api/real-build-flow/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/real-build-flow/request-approval/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/real-build-flow/request-approval">> = Specific
  const handler = {} as typeof import("../../app/api/real-build-flow/request-approval/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/real-build-flow/simulate-real/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/real-build-flow/simulate-real">> = Specific
  const handler = {} as typeof import("../../app/api/real-build-flow/simulate-real/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/real-execution/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/real-execution/approve">> = Specific
  const handler = {} as typeof import("../../app/api/real-execution/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/real-execution/dry-run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/real-execution/dry-run">> = Specific
  const handler = {} as typeof import("../../app/api/real-execution/dry-run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/real-execution/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/real-execution/execute">> = Specific
  const handler = {} as typeof import("../../app/api/real-execution/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/real-execution/request-approval/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/real-execution/request-approval">> = Specific
  const handler = {} as typeof import("../../app/api/real-execution/request-approval/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/creator/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/creator">> = Specific
  const handler = {} as typeof import("../../app/creator/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/design-partners/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/design-partners">> = Specific
  const handler = {} as typeof import("../../app/design-partners/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/founder-journey/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/founder-journey">> = Specific
  const handler = {} as typeof import("../../app/founder-journey/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
