import { createBackendFactory, createBackendFactoryInput } from "@/lib/build-platform/backend-factory";
import type { BuildContext } from "@/lib/build-platform/build-context";
import type { BuildDna } from "@/lib/build-platform/build-dna";
import { createDatabaseFactory, createDatabaseFactoryInput } from "@/lib/build-platform/database-factory";
import { createFrontendFactory, createFrontendFactoryInput } from "@/lib/build-platform/frontend-factory";
import {
  createInfrastructureFactory,
  createInfraFactoryInput,
} from "@/lib/build-platform/infrastructure-factory";
import { createQaFactory, createQaFactoryInput } from "@/lib/build-platform/qa-factory";
import type { ReleaseArtifacts, ReleaseArtifactRef } from "./types";

function blueprintStatus(valid: boolean, present: boolean): ReleaseArtifactRef["status"] {
  if (!present) return "missing";
  return valid ? "present" : "draft";
}

function buildDocumentation(
  ventureName: string,
  context: BuildContext,
): ReleaseArtifacts["documentation"] {
  const productPrd = context.sections.productPrd;
  const architecture = context.sections.architecture;
  const architectureData = architecture?.data;

  const prdNote =
    productPrd?.status === "complete" ? "PRD section complete." : "PRD section incomplete.";

  return {
    readme: `# ${ventureName}\n\nRelease package generated by ForgeOS Release Manager. Specs and artifacts only — no deploy execution.\n\n${prdNote}`,
    architectureOverview:
      architectureData && typeof architectureData === "object" && "summary" in architectureData
        ? String((architectureData as { summary?: string }).summary ?? "Architecture overview pending.")
        : "Architecture overview derived from Build Context sections.",
    apiSummary: "API surface defined in backend blueprint — endpoints, services, and security rules.",
    deploymentGuide:
      "Follow infrastructure spec and environment checklist. Credentials are placeholders only.",
  };
}

function buildEnvironmentChecklist(): ReleaseArtifacts["environmentChecklist"] {
  const environments = ["development", "staging", "production"] as const;
  const keys = [
    { id: "env-vars", label: "Environment variables documented (no real secrets)" },
    { id: "db-migrations", label: "Database migrations reviewed" },
    { id: "ci-pipeline", label: "CI/CD pipeline spec validated" },
    { id: "qa-gates", label: "QA gates configured in blueprint" },
    { id: "rollback-ready", label: "Rollback plan reviewed" },
  ];

  return environments.flatMap((environment) =>
    keys.map((key) => ({
      id: `${environment}-${key.id}`,
      environment,
      label: `[${environment}] ${key.label}`,
      required: environment !== "development",
      configured: environment === "development",
      notes: "Spec-only — configure in target environment before real deploy.",
    })),
  );
}

export function collectReleaseArtifacts(
  context: BuildContext,
  dna: BuildDna,
): ReleaseArtifacts {
  const frontendFactory = createFrontendFactory();
  const backendFactory = createBackendFactory();
  const databaseFactory = createDatabaseFactory();
  const qaFactory = createQaFactory();
  const infraFactory = createInfrastructureFactory();

  const frontendBlueprint = frontendFactory.generateBlueprint(
    createFrontendFactoryInput(context, dna),
  );
  const backendBlueprint = backendFactory.generateBlueprint(
    createBackendFactoryInput(context, dna),
  );
  const databaseBlueprint = databaseFactory.generateBlueprint(
    createDatabaseFactoryInput(context, dna),
  );
  const qaPlan = qaFactory.generateBlueprint(createQaFactoryInput(context, dna));
  const infrastructureSpec = infraFactory.generateBlueprint(
    createInfraFactoryInput(context, dna),
  );

  const documentation = buildDocumentation(context.meta.ventureName, context);
  const environmentChecklist = buildEnvironmentChecklist();

  const refs: ReleaseArtifactRef[] = [
    {
      id: "frontend-blueprint",
      label: "Frontend Blueprint",
      type: "frontend-blueprint",
      status: blueprintStatus(frontendBlueprint.validation.valid, true),
      summary: `${frontendBlueprint.routes.length} routes · ${frontendBlueprint.pages.length} pages`,
    },
    {
      id: "backend-blueprint",
      label: "Backend Blueprint",
      type: "backend-blueprint",
      status: blueprintStatus(backendBlueprint.validation.valid, true),
      summary: `${backendBlueprint.api.endpoints.length} endpoints · ${backendBlueprint.services.length} services`,
    },
    {
      id: "database-blueprint",
      label: "Database Blueprint",
      type: "database-blueprint",
      status: blueprintStatus(databaseBlueprint.validation.valid, true),
      summary: `${databaseBlueprint.entities.length} entities · ${databaseBlueprint.migrations.length} migrations`,
    },
    {
      id: "qa-plan",
      label: "QA Plan",
      type: "qa-plan",
      status: blueprintStatus(qaPlan.validation.valid, true),
      summary: `${qaPlan.testPlan.suites.length} suites · ${qaPlan.playwright.scenarios.length} e2e scenarios`,
    },
    {
      id: "infrastructure-spec",
      label: "Infrastructure Spec",
      type: "infrastructure-spec",
      status: blueprintStatus(infrastructureSpec.validation.valid, true),
      summary: `${infrastructureSpec.docker.services.length} docker services · ${infrastructureSpec.cicd.jobs.length} CI jobs`,
    },
    {
      id: "documentation",
      label: "Documentation",
      type: "documentation",
      status: "present",
      summary: "README, architecture, API summary, deployment guide",
    },
    {
      id: "environment-checklist",
      label: "Environment Checklist",
      type: "environment-checklist",
      status: "present",
      summary: `${environmentChecklist.length} checklist items across environments`,
    },
  ];

  return {
    frontendBlueprint,
    backendBlueprint,
    databaseBlueprint,
    qaPlan,
    infrastructureSpec,
    documentation,
    environmentChecklist,
    refs,
  };
}
