/** ForgeOS AI Orchestration — task registry. */

import type { OrchestrationTaskId, TaskDefinition } from "./types";

export const TASK_REGISTRY: Record<OrchestrationTaskId, TaskDefinition> = {
  CEO_BRIEF: {
    id: "CEO_BRIEF",
    program: "venture-intelligence",
    objective: "Generar briefing ejecutivo del venture.",
    outputFormat: "json",
    requiresJson: true,
    minimumContext: ["idea"],
    relatedWorker: "ceo",
    allowsMockFallback: true,
    gatewayTask: "ceo-brief",
  },
  CEO_REVIEW: {
    id: "CEO_REVIEW",
    program: "venture-intelligence",
    objective: "Revisión estratégica del estado del venture.",
    outputFormat: "json",
    requiresJson: true,
    minimumContext: ["idea"],
    relatedWorker: "ceo",
    allowsMockFallback: true,
    gatewayTask: "ceo-review",
  },
  CEO_PRIORITY: {
    id: "CEO_PRIORITY",
    program: "venture-intelligence",
    objective: "Priorizar acciones del fundador.",
    outputFormat: "json",
    requiresJson: true,
    minimumContext: ["idea"],
    relatedWorker: "ceo",
    allowsMockFallback: true,
    gatewayTask: "ceo-priority",
  },
  CEO_RISK: {
    id: "CEO_RISK",
    program: "venture-intelligence",
    objective: "Identificar riesgos estratégicos.",
    outputFormat: "json",
    requiresJson: true,
    minimumContext: ["idea"],
    relatedWorker: "ceo",
    allowsMockFallback: true,
    gatewayTask: "ceo-risk",
  },
  BOARD_DEBATE: {
    id: "BOARD_DEBATE",
    program: "venture-intelligence",
    objective: "Debate del board sobre una decisión.",
    outputFormat: "json",
    requiresJson: true,
    minimumContext: ["idea"],
    relatedWorker: "board",
    allowsMockFallback: true,
    gatewayTask: "board-debate",
  },
  BOARD_VOTE: {
    id: "BOARD_VOTE",
    program: "venture-intelligence",
    objective: "Voto formal del board.",
    outputFormat: "json",
    requiresJson: true,
    minimumContext: ["idea"],
    relatedWorker: "board",
    allowsMockFallback: true,
    gatewayTask: "board-vote",
  },
  BOARD_CONSENSUS: {
    id: "BOARD_CONSENSUS",
    program: "venture-intelligence",
    objective: "Consenso del board tras debate.",
    outputFormat: "json",
    requiresJson: true,
    minimumContext: ["idea"],
    relatedWorker: "board",
    allowsMockFallback: true,
    gatewayTask: "board-consensus",
  },
  BUILD_PLAN: {
    id: "BUILD_PLAN",
    program: "venture-execution",
    objective: "Plan de construcción técnica.",
    outputFormat: "json",
    requiresJson: true,
    minimumContext: ["idea"],
    relatedWorker: "build",
    allowsMockFallback: true,
    gatewayTask: "build-plan",
  },
  BUILD_ARCHITECTURE: {
    id: "BUILD_ARCHITECTURE",
    program: "venture-execution",
    objective: "Arquitectura del sistema.",
    outputFormat: "json",
    requiresJson: true,
    minimumContext: ["idea"],
    relatedWorker: "build",
    allowsMockFallback: true,
    gatewayTask: "build-architecture",
  },
  BUILD_BACKEND: {
    id: "BUILD_BACKEND",
    program: "venture-execution",
    objective: "Diseño del backend.",
    outputFormat: "json",
    requiresJson: true,
    minimumContext: ["idea"],
    relatedWorker: "build",
    allowsMockFallback: true,
    gatewayTask: "build-backend",
  },
  BUILD_FRONTEND: {
    id: "BUILD_FRONTEND",
    program: "venture-execution",
    objective: "Diseño del frontend.",
    outputFormat: "json",
    requiresJson: true,
    minimumContext: ["idea"],
    relatedWorker: "build",
    allowsMockFallback: true,
    gatewayTask: "build-frontend",
  },
  BUILD_DATABASE: {
    id: "BUILD_DATABASE",
    program: "venture-execution",
    objective: "Modelo de datos.",
    outputFormat: "json",
    requiresJson: true,
    minimumContext: ["idea"],
    relatedWorker: "build",
    allowsMockFallback: true,
    gatewayTask: "build-database",
  },
  BUILD_DEPLOY: {
    id: "BUILD_DEPLOY",
    program: "venture-execution",
    objective: "Estrategia de despliegue.",
    outputFormat: "json",
    requiresJson: true,
    minimumContext: ["idea"],
    relatedWorker: "build",
    allowsMockFallback: true,
    gatewayTask: "build-deploy",
  },
  BUILD_QA: {
    id: "BUILD_QA",
    program: "venture-execution",
    objective: "Plan de QA y testing.",
    outputFormat: "json",
    requiresJson: true,
    minimumContext: ["idea"],
    relatedWorker: "build",
    allowsMockFallback: true,
    gatewayTask: "build-qa",
  },
};

export function getTaskDefinition(taskId: OrchestrationTaskId): TaskDefinition {
  return TASK_REGISTRY[taskId];
}

export function listOrchestrationTasks(): TaskDefinition[] {
  return Object.values(TASK_REGISTRY);
}
