import { NextResponse } from "next/server";
import {
  generatePeriodReport,
  getReportsCenterSnapshot,
} from "@/lib/investment/reports-generator";
import { REPORT_PERIOD_TYPES, type ReportPeriodType } from "@/lib/investment/reports-types";
import {
  generateDailyTelegramReport,
  generateMorningTelegramReport,
  generateWeeklyTelegramReport,
  getTelegramReportsStatus,
  maybeSendScheduledReports,
} from "@/lib/notifications/report-generator";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

function isPeriodType(value: string): value is ReportPeriodType {
  return (REPORT_PERIOD_TYPES as readonly string[]).includes(value);
}

function isTelegramType(value: string | null): value is "daily" | "weekly" | "auto" | "morning" {
  return value === "daily" || value === "weekly" || value === "auto" || value === "morning";
}

/**
 * GET /api/investment/reports
 * - ?telegram=1 → last Telegram report status / preview
 * - default → Reports Center snapshot (ANALYSIS_ONLY)
 */
export async function GET(request: Request) {
  try {
    const sp = new URL(request.url).searchParams;
    if (sp.get("telegram") === "1" || sp.get("channel") === "telegram") {
      return NextResponse.json({
        ...getTelegramReportsStatus(),
        orderExecution: "disabled",
        liveTradingEnabled: false,
      });
    }

    const autoEnsure = sp.get("autoEnsure") !== "0";
    const snapshot = await getReportsCenterSnapshot({
      autoEnsure,
      selectedId: sp.get("id") ?? undefined,
      compareId: sp.get("compare") ?? undefined,
      filters: {
        periodType: sp.get("periodType") ?? undefined,
        periodKey: sp.get("periodKey") ?? undefined,
        q: sp.get("q") ?? undefined,
        from: sp.get("from") ?? undefined,
        to: sp.get("to") ?? undefined,
        limit: Number(sp.get("limit") ?? 100) || 100,
      },
    });
    return NextResponse.json(snapshot);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Reports center failed";
    return NextResponse.json(
      {
        error: message,
        generatedAt: new Date().toISOString(),
        mode: "ANALYSIS_ONLY",
        orderExecution: "disabled",
        liveTradingEnabled: false,
        autoGenerated: [],
        total: 0,
        items: [],
        selected: null,
        compareWith: null,
        availablePeriodKeys: [],
        note: message,
      },
      { status: 200 },
    );
  }
}

/**
 * POST /api/investment/reports
 * - ?type=morning|daily|weekly|auto → Telegram report generate / scheduled send
 * - body { periodType, periodKey? } → immutable Reports Center period report
 *
 * ANALYSIS_ONLY — never triggers orders.
 */
export async function POST(request: Request) {
  try {
    const url = new URL(request.url);
    const telegramType = url.searchParams.get("type");

    if (isTelegramType(telegramType)) {
      const force = url.searchParams.get("force") === "1";
      const sendParam = url.searchParams.get("send");
      const send = sendParam === "0" ? false : sendParam === "1" ? true : telegramType === "auto";

      if (telegramType === "auto") {
        const scheduled = await maybeSendScheduledReports();
        return NextResponse.json({
          ...scheduled,
          orderExecution: "disabled",
          liveTradingEnabled: false,
          note: "Scheduled Telegram reports (Europe/Madrid) with PDF attachments.",
        });
      }

      if (telegramType === "morning") {
        const report = await generateMorningTelegramReport({ send, force });
        return NextResponse.json({
          ...report,
          orderExecution: "disabled",
          liveTradingEnabled: false,
        });
      }

      if (telegramType === "daily") {
        const report = await generateDailyTelegramReport({ send, force });
        return NextResponse.json({
          ...report,
          orderExecution: "disabled",
          liveTradingEnabled: false,
        });
      }

      const report = await generateWeeklyTelegramReport({ send, force });
      return NextResponse.json({
        ...report,
        orderExecution: "disabled",
        liveTradingEnabled: false,
      });
    }

    let body: { periodType?: string; periodKey?: string } = {};
    try {
      body = (await request.json()) as typeof body;
    } catch {
      body = {};
    }
    const periodTypeRaw = body.periodType ?? "daily";
    if (!isPeriodType(periodTypeRaw)) {
      return NextResponse.json(
        {
          error: `Invalid periodType. Expected one of: ${REPORT_PERIOD_TYPES.join(", ")} (or ?type=morning|daily|weekly|auto for Telegram)`,
          mode: "ANALYSIS_ONLY",
          orderExecution: "disabled",
        },
        { status: 400 },
      );
    }
    const report = await generatePeriodReport({
      periodType: periodTypeRaw,
      periodKey: body.periodKey,
    });
    return NextResponse.json({
      mode: "ANALYSIS_ONLY",
      orderExecution: "disabled",
      liveTradingEnabled: false,
      report,
      note: "Appended immutable report version. Prior ids untouched.",
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Report generation failed";
    return NextResponse.json(
      {
        error: message,
        mode: "ANALYSIS_ONLY",
        orderExecution: "disabled",
        liveTradingEnabled: false,
      },
      { status: 200 },
    );
  }
}
